print("------------------------------------------------")
print("Sistema de Cálculo de Hipotenusa")
print("------------------------------------------------")
cateto_oposto = int(input("Digite o valor do cateto oposto:\n "))
cateto_adjacente = int(input("Digite o valor do cateto adjacente:\n "))
hipotenusa = (((cateto_oposto**2) + (cateto_adjacente**2))**0.5)
print("="*40)
print(f'A Hipotenusa é igual a: {hipotenusa}')
print("="*40)